# This rule is not used by the project ktunnels itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ktunnels.int128.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ktunnels
    app.kubernetes.io/managed-by: kustomize
  name: proxy-admin-role
rules:
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies
  verbs:
  - '*'
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies/status
  verbs:
  - get
